### ISSUE TITLE
API not working on production server

### ISSUE THREAD

**Issue by BlueberryTech123** [ivandotv/radio-browser-api#118]
My website only appears to work whenever I'm hosting via localhost but not on actual production servers
The URL for the website is [here](https://jambox.onrender.com/). 

![image](https://github.com/ivandotv/radio-browser-api/assets/32250628/27256b18-e845-45ac-86c4-0c8ad88eebc2)

![image](https://github.com/ivandotv/radio-browser-api/assets/32250628/9e8a9230-7b0b-40c0-b8db-9ffa3d70da26)

But the thing is, the thing just stops working as soon as it gets to actually getting the stations. Here's what the output is *supposed* to look like:
![image](https://github.com/ivandotv/radio-browser-api/assets/32250628/a7440e3c-4458-48b8-ade9-820ad82cea48)

And here is what the output on the production server looks like (Notice how it doesn't output "Done!" or the station data):
![image](https://github.com/ivandotv/radio-browser-api/assets/32250628/b9ad59d2-7788-4053-9aae-749706c8be9c)

I know that this page is kinda dead tho

**Comment by ivandotv** [comment]
Please post actual errors, not screenshots.
