### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by kaaax0815** [ivandotv/radio-browser-api#47]
```
Could not find a declaration file for module 'radio-browser-api'. 'd:/Bernd/BerndPC/Documents/Github/Typescript/Discord-MusicBot/node_modules/radio-browser-api/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/radio-browser-api` if it exists or add a new declaration (.d.ts) file containing `declare module 'radio-browser-api';`
```

This error occurs when importing the module in a Typescript Project: `import { RadioBrowserApi } from 'radio-browser-api';`

I found out that the `types` directory is missing in the npm module because the `build:types` script is not included in the `build` script

**Comment by ivandotv** [comment]
Good catch. Thanks.
