### ISSUE TITLE
Inconsistency with search options

### ISSUE THREAD

**Issue by haecksenwerk** [ivandotv/radio-browser-api#77]
I use the following search options to query stations:

```
stations = await api.searchStations({
          name: searchTerm,
          tag: "",
          language: "",
          countryCode: "",
```

If I understand it correctly, the params 'name', 'tag', and 'language' are linked via an AND operation, and when a parm is set to an empty string then it no longer has any filtering effect. I would expect the same behavior from the 'countryCode' parm, but when set to an empty string it limits the results to a few stations that do not have a countryCode defined, instead of allowing all stations, while the parameter operates as expected when having a country-code assigned. Is this intentional or might it be a bug?

I have also difficulties with the bitrateMin and bitrateMax query options. No matter if I assign a bitrate, for example 128, as integer or as string, it has no effect.

**Comment by ivandotv** [comment]
I'm not sure that this has anything to do with the library, it is the way the API works, which I have no control over.
Have you tried setting the `countryCode` to `undefined` instead of the empty string? That way `countryCode` would be omitted from the query. Would that give you the expected results?

**Comment by haecksenwerk** [comment]
Thanks for your swift reply. Setting the countryCode to 'undefined' breaks it, so I get no results at all. Maybe the API documents on radio-browser.info give some information about it, I'll have a look at them tomorrow.

**Comment by ivandotv** [comment]
Okay, let me know how it goes.
Also, try looking in the `network` tab in the browser dev tools, and then copy/paste the request directly in the browser and see what you get (firefox will format JSON response automatically).  That way you can quickly debug the parameters.

**Comment by haecksenwerk** [comment]
You're right, the issue is seemingly not related to the wrapper code. 
For the time being, I simply worked around it by introducing a separate query-set for ```countryCode```.
So I close the issue but will still report here if there are some findings for the root cause.

**Comment by purecodework** [comment]
> You're right, the issue is seemingly not related to the wrapper code. For the time being, I simply worked around it by introducing a separate query-set for `countryCode`. So I close the issue but will still report here if there are some findings for the root cause.

I am also experiencing this inconsistency. 
If I leave the "state" query parameter to an empty string, then the API works as expected. 
But the behavior of "countryCode" is different from the "state". 

 I wonder if you have found the cause of it. Please let me know if you found it, thanks!

**Comment by haecksenwerk** [comment]
@purecodework Admittedly, I lack the knowledge to track down the root cause, since I started with React just a few months ago, plus I haven't got my feet wet withTypescript yet. As mentioned, I worked around the `countryCode` issue with a separate query set, so it works for me. But unfortunately, I still wasn't successful with using the `bitrateMin` and `bitrateMax` settings for filtering the results. Have you been able to apply them?

**Comment by purecodework** [comment]
> @purecodework Admittedly, I lack the knowledge to track down the root cause, since I started with React just a few months ago, plus I haven't got my feet wet withTypescript yet. As mentioned, I worked around the `countryCode` issue with a separate query set, so it works for me. But unfortunately, I still wasn't successful with using the `bitrateMin` and `bitrateMax` settings for filtering the results. Have you been able to apply them?

This is my first project with Typescript haha. For the country code, I did the similar thing as you do by adding a condition check. I tried for a while with the bitrateMin and bitrateMax after I saw your comment, but unfortunately I can't get them to work either.

**Comment by ivandotv** [comment]
The underlying API service is inconsistent with the results. Try calling the API  directly as I suggested in this[comment](https://github.com/ivandotv/radio-browser-api/issues/77#issuecomment-1018031066), and see if that gives you the correct results.
If that's the case, than maybe something is wrong with my implementation
