### ISSUE TITLE
Api calls not returning sometimes

### ISSUE THREAD

**Issue by rakeshparveen5** [ivandotv/radio-browser-api#88]
I am using the radio browser apis in one of my flutter app. Using the library [http](https://pub.dev/packages/http) for api call.
I am calling [Get Countries](http://serverNamefromServersList/json/countries) and [Get Languages](http://serverNamefromServersList/json/languages) in my flutter app, But sometimes these api take more then a minute to return the response or does not return for a long time.

I tested my code by using some another testing api urls (https://reqres.in/api/users?page=2) in the same code and that are working fine. Having issue with radiobrowser api only.
Any fix or suggestions regarding this ?

**Comment by ivandotv** [comment]
Or you are using this Javascript module inside a flutter app? 
Can you show me the usage example?

**Comment by rakeshparveen5** [comment]
I am using api endpoints un my flutter app.
Attached screenshot for reference 
![Screenshot_20220324-221534_Chrome](https://user-images.githubusercontent.com/14840258/159968258-e4011dc9-0526-47bc-aad4-0c742cfd3e30.jpg)

**Comment by ivandotv** [comment]
I'm not in control of the API servers, I just maintain the library. You should contact the owner of the servers. 
https://fr1.api.radio-browser.info/
