### ISSUE TITLE
tagList seems to be ignored

### ISSUE THREAD

**Issue by ghummer** [ivandotv/radio-browser-api#95]
it seems like the tagList is ignored. could it be that the param is lowercase but the radio-browser api is expecting it as `tagList`?

**Comment by ivandotv** [comment]
Can you give me more details? 
This code works:
```js
const api = new RadioBrowserApi('appname')

api.searchStations({ tagList: ['dance', 'house'] ,limit:2}).then((stations) => console.log(stations))
```

https://replit.com/@ivanvlatkovic/Radio-browser-api-tag-test#index.js

**Comment by ghummer** [comment]
True, while it does return results, the results do not contain the tags requested. It's basically the same result you would get if you would not have sent the tags. I saw that prior to sending the request the request url is lowercased, I then tried to request the same search with `tagList` as the parameter and then it returned stations that do contain the requested tags.
