### ISSUE TITLE
Metro has encountered an error: While trying to resolve module `radio-browser-api` 

### ISSUE THREAD

**Issue by barii64** [ivandotv/radio-browser-api#99]
I'm trying to use it with react native but have a problem. Can you help me? 
![image](https://user-images.githubusercontent.com/37247941/167492654-b84ba160-b206-4f97-a523-5bd8112e84af.png)

**Comment by ivandotv** [comment]
That is a Facebook Metro issue with loading the `.cjs` files. 
I believe you need to set up Metro to recognize the `.cjs` files.
Take a look at this issue:  https://github.com/facebook/metro/issues/535
